# Generated by Django 2.2.7 on 2019-11-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20191130_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farms',
            name='x1',
        ),
        migrations.RemoveField(
            model_name='farms',
            name='x2',
        ),
        migrations.RemoveField(
            model_name='farms',
            name='x3',
        ),
        migrations.RemoveField(
            model_name='farms',
            name='x4',
        ),
        migrations.RemoveField(
            model_name='farms',
            name='y1',
        ),
        migrations.RemoveField(
            model_name='farms',
            name='y2',
        ),
        migrations.RemoveField(
            model_name='farms',
            name='y3',
        ),
        migrations.RemoveField(
            model_name='farms',
            name='y4',
        ),
        migrations.AddField(
            model_name='farms',
            name='cords',
            field=models.CharField(default='1', max_length=500),
            preserve_default=False,
        ),
    ]
