# Generated by Django 2.2.7 on 2019-11-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20191130_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='farms',
            name='farm_center',
            field=models.CharField(default='1', max_length=500),
            preserve_default=False,
        ),
    ]
