# Generated by Django 2.2.7 on 2019-12-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_farms_farm_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farms',
            name='sustainable',
            field=models.BooleanField(blank=True),
        ),
    ]
